### ISSUE TITLE
Compile

### ISSUE THREAD

**Issue by fourseaLee** [xDimon/soralog#2]
Compile error ！Because “filesystem”
![图片](https://user-images.githubusercontent.com/25864430/122021787-96c4de80-cdf8-11eb-8379-ef7aaf0ddc71.png)
It should be compatible C++ standard ，    
“#include <experimental/filesystem>
 namespace fs = std::experimental::filesystem; ”

**Comment by xDimon** [comment]
Next version will support GNU compilers at least version 8.0. Unfortunatelly g++ v7 is not supported and does not plan.

**Comment by xDimon** [comment]
> Next version will support GNU compilers at least version 8.0. Unfortunatelly g++ v7 is not supported and does not plan.

done
